In [34]:
import pandas as pd

In [35]:
df = pd.read_csv(
    "data/production_electricite_par_filiere.csv",
    sep=";",
)

In [36]:
df

,Territoire,Statut,Date,Production totale (MW),Thermique (MW),Bagasse/charbon (MW),Hydraulique (MW),Micro-hydraulique (MW),Solaire photovoltaïque (MW),Eolien (MW),Bioénergies (MW),Géothermie (MW),Importations (MW),Coût moyen de production (€/MWh)
0,Guyane,Validé,2018-12-31T23:00:00+00:00,86.130000,40.290000,NaN,45.380000,NaN,0.000000,NaN,0.460000,NaN,NaN,303.360802
1,Réunion,Validé,2018-12-31T23:00:00+00:00,279.020000,52.940000,160.080000,64.300000,NaN,-0.450000,0.440000,1.700000,NaN,NaN,192.559168
2,Martinique,Validé,2018-12-31T23:00:00+00:00,138.450000,103.270000,NaN,0.000000,NaN,-0.090000,6.740000,28.540000,NaN,NaN,286.226926
3,Corse,Validé,2018-12-31T23:00:00+00:00,339.880000,139.890000,NaN,49.750000,7.1500,-0.290000,-0.020000,0.990000,NaN,142.41000,163.449660
4,Guadeloupe,Validé,2018-12-31T23:00:00+00:00,156.400000,91.320000,40.030000,5.420000,NaN,-0.090000,3.780000,2.110000,13.83,NaN,245.322751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219115,Corse,Estimé,2023-12-31T22:00:00+00:00,294.947812,159.999334,NaN,59.373055,6.0655,-0.907993,10.554833,0.362333,NaN,59.50075,NaN
219116,Guadeloupe,Estimé,2023-12-31T22:00:00+00:00,149.313266,80.703266,23.820000,0.540000,NaN,0.130000,0.910000,30.240000,12.97,NaN,NaN
219117,Guyane,Estimé,2023-12-31T22:00:00+00:00,98.689592,35.400590,NaN,53.507156,NaN,-0.180995,NaN,9.962841,NaN,NaN,NaN
219118,Martinique,Estimé,2023-12-31T22:00:00+00:00,139.516323,102.973000,NaN,0.000000,NaN,-0.116677,1.382000,35.278000,NaN,NaN,NaN
219119,Réunion,Estimé,2023-12-31T22:00:00+00:00,322.483542,160.060114,120.015572,40.678679,NaN,-1.865236,3.594413,NaN,NaN,NaN,NaN

In [37]:
df["Territoire"].unique()

df = df[df["Territoire"].isin(["Guyane", "Réunion", "Martinique", "Guadeloupe"])]

In [38]:
df["Date"] = pd.to_datetime(df["Date"])

/tmp/ipykernel_98830/936118274.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"])

In [39]:
import datetime

df_train = df[
    (df["Date"] >= pd.Timestamp(datetime.datetime(2019, 1, 1), tz="UTC"))
    & (df["Date"] < pd.Timestamp(datetime.datetime(2019, 12, 29), tz="UTC"))
]

df_test = df[
    (df["Date"] >= pd.Timestamp(datetime.datetime(2019, 12, 29), tz="UTC"))
    & (df["Date"] < pd.Timestamp(datetime.datetime(2020, 1, 1), tz="UTC"))
]

In [40]:
df_train

,Territoire,Statut,Date,Production totale (MW),Thermique (MW),Bagasse/charbon (MW),Hydraulique (MW),Micro-hydraulique (MW),Solaire photovoltaïque (MW),Eolien (MW),Bioénergies (MW),Géothermie (MW),Importations (MW),Coût moyen de production (€/MWh)
5,Réunion,Validé,2019-01-01 00:00:00+00:00,299.21,62.21,168.59,66.67,NaN,-0.43,0.47,1.70,NaN,NaN,194.044288
6,Martinique,Validé,2019-01-01 00:00:00+00:00,131.87,95.24,NaN,0.00,NaN,-0.09,6.51,30.21,NaN,NaN,295.968713
7,Guadeloupe,Validé,2019-01-01 00:00:00+00:00,152.19,86.03,40.70,5.38,NaN,-0.10,4.22,2.11,13.84,NaN,244.842654
9,Guyane,Validé,2019-01-01 00:00:00+00:00,84.77,40.18,NaN,43.98,NaN,0.00,NaN,0.61,NaN,NaN,305.721167
10,Guyane,Validé,2019-01-01 01:00:00+00:00,82.43,39.68,NaN,42.21,NaN,0.00,NaN,0.54,NaN,NaN,308.024401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43439,Martinique,Validé,2019-12-28 22:00:00+00:00,154.85,122.67,NaN,0.00,NaN,-0.16,6.22,26.13,NaN,NaN,281.302547
43441,Guyane,Validé,2019-12-28 23:00:00+00:00,100.50,33.95,NaN,65.16,NaN,0.00,NaN,1.40,NaN,NaN,255.351958
43442,Guadeloupe,Validé,2019-12-28 23:00:00+00:00,170.66,79.24,66.32,4.92,NaN,-0.14,3.96,2.24,14.12,NaN,250.684081
43443,Réunion,Validé,2019-12-28 23:00:00+00:00,303.29,46.87,191.17,60.84,NaN,-0.50,2.36,2.55,NaN,NaN,192.117886
43444,Martinique,Validé,2019-12-28 23:00:00+00:00,144.74,112.42,NaN,0.00,NaN,-0.15,5.74,26.73,NaN,NaN,281.855433

In [41]:
df_test

,Territoire,Statut,Date,Production totale (MW),Thermique (MW),Bagasse/charbon (MW),Hydraulique (MW),Micro-hydraulique (MW),Solaire photovoltaïque (MW),Eolien (MW),Bioénergies (MW),Géothermie (MW),Importations (MW),Coût moyen de production (€/MWh)
43445,Martinique,Validé,2019-12-29 00:00:00+00:00,137.22,105.62,NaN,0.00,NaN,-0.16,5.19,26.56,NaN,NaN,282.526122
43446,Guadeloupe,Validé,2019-12-29 00:00:00+00:00,163.47,80.01,59.26,4.91,NaN,-0.20,3.12,2.25,14.13,NaN,250.163945
43447,Guyane,Validé,2019-12-29 00:00:00+00:00,96.41,33.50,NaN,61.54,NaN,0.00,NaN,1.36,NaN,NaN,258.549262
43449,Réunion,Validé,2019-12-29 00:00:00+00:00,283.33,45.80,176.47,56.75,NaN,-0.48,2.25,2.55,NaN,NaN,192.326933
43451,Guyane,Validé,2019-12-29 01:00:00+00:00,93.89,33.11,NaN,59.39,NaN,0.00,NaN,1.39,NaN,NaN,260.359506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43799,Réunion,Validé,2019-12-31 22:00:00+00:00,332.39,59.63,186.61,84.17,NaN,-0.52,-0.05,2.54,NaN,NaN,190.241538
43800,Guadeloupe,Validé,2019-12-31 23:00:00+00:00,167.56,98.49,51.98,4.53,NaN,-0.18,0.12,2.27,10.35,NaN,NaN
43801,Martinique,Validé,2019-12-31 23:00:00+00:00,144.62,113.56,NaN,0.00,NaN,-0.23,1.27,30.02,NaN,NaN,NaN
43802,Réunion,Validé,2019-12-31 23:00:00+00:00,310.29,33.50,189.94,84.87,NaN,-0.48,-0.06,2.51,NaN,NaN,NaN
43803,Guyane,Validé,2019-12-31 23:00:00+00:00,97.10,48.26,NaN,47.53,NaN,-0.09,NaN,1.40,NaN,NaN,NaN

In [44]:
df_train.to_csv(
    "train_production_electricite_par_filiere.csv",
    sep=";",
    index=False,
    header=True,
)

In [45]:
df_test.to_csv(
    "test_production_electricite_par_filiere.csv",
    sep=";",
    index=False,
    header=True,
)