In [2]:
import pandas as pd

In [3]:
df_1 = pd.read_csv("data/synop.201901.csv", sep=";")
df_2 = pd.read_csv("data/synop.201902.csv", sep=";")
df_3 = pd.read_csv("data/synop.201903.csv", sep=";")

In [4]:
df_2.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,Unnamed: 59
0,7005,20190201000000,98360,0,4,120,3.100000,273.550000,273.250000,98,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
1,7015,20190201000000,98500,-190,6,80,6.500000,272.650000,272.350000,98,...,8,mq,240,mq,mq,mq,mq,mq,mq,NaN
2,7020,20190201000000,98000,270,1,260,6.500000,280.450000,277.250000,80,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
3,7027,20190201000000,98260,120,3,200,4.000000,276.250000,274.250000,87,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
4,7037,20190201000000,98410,120,3,180,4.800000,274.850000,274.550000,98,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN

In [5]:
df = pd.concat([df_1, df_2, df_3], ignore_index=True)

In [6]:
df.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,...,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,Unnamed: 59
0,7005,20190101000000,103510,-70,6,270,2.200000,281.250000,279.250000,87,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
1,7015,20190101000000,103460,-70,7,250,2.900000,280.350000,278.650000,89,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
2,7020,20190101000000,mq,-50,5,mq,mq,mq,mq,mq,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
3,7027,20190101000000,103690,-50,6,290,2.800000,281.350000,279.350000,87,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN
4,7037,20190101000000,103620,-60,8,270,1.900000,279.950000,279.250000,95,...,mq,mq,mq,mq,mq,mq,mq,mq,mq,NaN

In [7]:
df["date"] = pd.to_datetime(df["date"], format="%Y%m%d%H%M%S")

In [8]:
df.date.min()

Timestamp('2019-01-01 00:00:00')

In [9]:
df.date.max()

Timestamp('2019-03-31 21:00:00')

In [10]:
df.columns

Index(['numer_sta', 'date', 'pmer', 'tend', 'cod_tend', 'dd', 'ff', 't', 'td',
       'u', 'vv', 'ww', 'w1', 'w2', 'n', 'nbas', 'hbas', 'cl', 'cm', 'ch',
       'pres', 'niv_bar', 'geop', 'tend24', 'tn12', 'tn24', 'tx12', 'tx24',
       'tminsol', 'sw', 'tw', 'raf10', 'rafper', 'per', 'etat_sol', 'ht_neige',
       'ssfrai', 'perssfrai', 'rr1', 'rr3', 'rr6', 'rr12', 'rr24', 'phenspe1',
       'phenspe2', 'phenspe3', 'phenspe4', 'nnuage1', 'ctype1', 'hnuage1',
       'nnuage2', 'ctype2', 'hnuage2', 'nnuage3', 'ctype3', 'hnuage3',
       'nnuage4', 'ctype4', 'hnuage4', 'Unnamed: 59'],
      dtype='object')

In [11]:
mapping_dict = {
    "numer_sta": "station_id",
    "date": "date",
    "pmer": "sea_level_pressure_pa",
    "tend": "pressure_change_3h_pa",
    "cod_tend": "barometric_trend_type_code",
    "dd": "wind_direction_10min_deg",
    "ff": "wind_speed_10min_ms",
    "t": "temperature_k",
    "td": "dew_point_k",
    "u": "humidity_percent",
    "vv": "horizontal_visibility_m",
    "ww": "current_weather_code",
    "w1": "past_weather_1_code",
    "w2": "past_weather_2_code",
    "n": "total_cloud_cover_percent",
    "nbas": "low_cloud_cover_octa",
    "hbas": "low_cloud_base_height_m",
    "cl": "low_cloud_type_code",
    "cm": "mid_cloud_type_code",
    "ch": "high_cloud_type_code",
    "pres": "station_pressure_pa",
    "niv_bar": "barometric_level_pa",
    "geop": "geopotential_m2s2",
    "tend24": "pressure_change_24h_pa",
    "tnN": "min_temperature_n_hours_k",
    "txN": "max_temperature_n_hours_k",
    "tminsol": "min_ground_temperature_12h_k",
    "sw": "measurement_method_code",
    "tw": "wet_bulb_temperature_k",
    "raf10": "wind_gusts_10min_ms",
    "rafper": "wind_gusts_period_ms",
    "per": "gust_measurement_period_min",
    "etat_sol": "ground_state_code",
    "ht_neige": "total_snow_ice_height_m",
    "ssfrai": "fresh_snow_height_m",
    "perssfrai": "fresh_snow_measurement_period_tenths_of_hour",
    "rrN": "precipitation_n_hours_mm",
    "phenspeN": "special_phenomenon_code",
    "nnuageN": "cloud_cover_layer_n_octa",
    "etypeN": "cloud_type_n_code",
    "hnuageN": "cloud_base_height_n_m",
}

In [12]:
df = df.rename(mapping_dict, axis=1)

In [13]:
df_select = df[
    [
        "station_id",
        "date",
        "total_cloud_cover_percent",
        "low_cloud_cover_octa",
        "temperature_k",
        "humidity_percent",
        "horizontal_visibility_m",
        "wet_bulb_temperature_k",
        "low_cloud_type_code",
        "mid_cloud_type_code",
        "high_cloud_type_code",
    ]
]

In [14]:
df_select

,station_id,date,total_cloud_cover_percent,low_cloud_cover_octa,temperature_k,humidity_percent,horizontal_visibility_m,wet_bulb_temperature_k,low_cloud_type_code,mid_cloud_type_code,high_cloud_type_code
0,7005,2019-01-01 00:00:00,mq,mq,281.250000,87,14860,mq,mq,mq,mq
1,7015,2019-01-01 00:00:00,100,8,280.350000,89,18140,mq,mq,mq,mq
2,7020,2019-01-01 00:00:00,mq,mq,mq,mq,mq,mq,mq,mq,mq
3,7027,2019-01-01 00:00:00,100,8,281.350000,87,29820,mq,mq,mq,mq
4,7037,2019-01-01 00:00:00,100,8,279.950000,95,11450,mq,mq,mq,mq
...,...,...,...,...,...,...,...,...,...,...,...
43090,81401,2019-03-31 21:00:00,mq,mq,301.350000,66,mq,mq,mq,mq,mq
43091,81405,2019-03-31 21:00:00,mq,2,301.450000,68,36190,mq,mq,mq,mq
43092,81408,2019-03-31 21:00:00,mq,mq,302.450000,65,mq,mq,mq,mq,mq
43093,81415,2019-03-31 21:00:00,mq,mq,305.250000,53,mq,mq,mq,mq,mq
43094,89642,2019-03-31 21:00:00,100,mq,266.050000,51,20000,mq,mq,mq,mq

In [15]:
id_station_mapping = {
    "67005": "Réunion",
    "71805": "Martinique",
    "78890": "Guadeloupe",
    "78922": "Martinique",
    "78925": "Martinique",
    "81401": "Guyane",
    "81405": "Guyane",
    "81408": "Guyane",
    "81415": "Guyane",
}

df_select["station_id"] = df_select["station_id"].astype(str)

df_select["station_name"] = df_select["station_id"].map(id_station_mapping)

/tmp/ipykernel_6030/3829876817.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["station_id"] = df_select["station_id"].astype(str)
/tmp/ipykernel_6030/3829876817.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["station_name"] = df_select["station_id"].map(id_station_mapping)

In [21]:
df_select = df_select.dropna(subset=["station_name"])

# Replace all "mq" values with None in all the dataframe
df_select = df_select.replace("mq", None)
df_select["total_cloud_cover_percent"] = df_select["total_cloud_cover_percent"].astype(
    float
)
df_select["low_cloud_cover_octa"] = df_select["low_cloud_cover_octa"].astype(float)
df_select["temperature_k"] = df_select["temperature_k"].astype(float)
df_select["humidity_percent"] = df_select["humidity_percent"].astype(float)
df_select["horizontal_visibility_m"] = df_select["horizontal_visibility_m"].astype(
    float
)
df_select["wet_bulb_temperature_k"] = df_select["wet_bulb_temperature_k"].astype(float)

In [22]:
df_select_gr = df_select.groupby(
    ["station_id", "station_name", "date"], as_index=False
).agg(
    {
        "total_cloud_cover_percent": "mean",
        "low_cloud_cover_octa": "mean",
        "temperature_k": "mean",
        "humidity_percent": "mean",
        "horizontal_visibility_m": "mean",
        "wet_bulb_temperature_k": "mean",
    }
)

In [23]:
df_select_gr.head()

,station_id,station_name,date,total_cloud_cover_percent,low_cloud_cover_octa,temperature_k,humidity_percent,horizontal_visibility_m,wet_bulb_temperature_k
0,67005,Réunion,2019-01-01 00:00:00,100.0,8.0,300.45,81.0,20000.0,NaN
1,67005,Réunion,2019-01-01 18:00:00,NaN,0.0,301.25,85.0,20000.0,NaN
2,67005,Réunion,2019-01-02 00:00:00,100.0,8.0,300.35,86.0,20000.0,NaN
3,67005,Réunion,2019-01-02 06:00:00,90.0,7.0,303.75,73.0,20000.0,NaN
4,67005,Réunion,2019-01-02 15:00:00,90.0,1.0,301.65,79.0,20000.0,NaN